all: main

main: operacionesMatriciales.cpp operacionesMatriciales.h inputOutput.cpp inputOutput.h simulacionRayos.cpp simulacionRayos.h main.cpp 
	g++ operacionesMatriciales.cpp inputOutput.cpp simulacionRayos.cpp main.cpp -o main
